yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/', views.all_groups, name='all_groups'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace = 'posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.PROTECT
    )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group


def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def all_groups(request):
    return render(request, 'posts/all_groups.html')


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)

    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html>
{% load static %} 
<html lang="ru">          
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>{% block title %} Титл не робит {% endblock %}</title>       
  </head>
  <body>     
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не опдвезли :( 
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
<footer class="bg-light text-center text-lg-start">
    <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <h class="text-dark" href="https://mdbootstrap.com/"><span style="color:red">Ya</span>tube</p></h>
  </div>
</footer>

yatube/templates/includes/header.html
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href='{%url 'posts:index' %}'>
    <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    <span style="color:red">Ya</span>tube</a>
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="{%url 'posts:index' %}">Главная страница</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{%url 'posts:all_groups' %}">Сообщества</a>
    </li>
  </ul>
</div>
</nav>

yatube/templates/posts/all_groups.html
{% extends 'base.html' %}
{% block title %}
  Yatube
{% endblock %}     
{% block content %}
  Сообщества
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.slug }}
{% endblock %}
{% block content %}
  {% for post in posts %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}     
{% block content %}
  <h2>Главная страница Yatube</h2><hr>
  {% for post in posts %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% if post.group %}
    <a href="{%url 'posts:group_posts' post.group.slug %}" class="btn btn-secondary" role="button">Все записи группы</a>    
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}